# Generated by Django 3.1.3 on 2020-11-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='nombre',
        ),
    ]
