# Generated by Django 3.1.3 on 2020-11-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_ubicacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=64),
            preserve_default=False,
        ),
    ]
