# Generated by Django 3.1.3 on 2020-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_ubicacion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('documento', models.IntegerField()),
                ('direccion', models.CharField(max_length=64)),
                ('correo', models.IntegerField(max_length=10)),
            ],
        ),
    ]
